name: Spring Boot CI (Java 17 + Maven)

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      KAFKA_ENABLED: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Start Kafka & Zookeeper with Docker Compose
        run: docker-compose -f docker/docker-compose.yml up -d

      - name: Wait for Kafka & Zookeeper to be ready
        run: sleep 20

      - name: Run Tests with Maven
        run: mvn --batch-mode --update-snapshots clean test
